export let products=[
  {
    id: 1,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2014",
    year: 2014,
    month: "Jan",
  },
  {
    id: 2,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2014",
    year: 2014,
    month: "Feb",
  },
  {
    id: 3,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Mar 2014",
    year: 2014,
    month: "Mar",
  },
  {
    id: 4,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2015",
    year: 2015,
    month: "Jan",
  },
  {
    id: 5,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2015",
    year: 2015,
    month: "Feb",
  },
  {
    id: 6,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2016",
    year: 2016,
    month: "Jan",
  },
  {
    id: 7,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2016",
    year: 2016,
    month: "Feb",
  },
  {
    id: 8,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2017",
    year: 2017,
    month: "Feb",
  },
  {
    id: 9,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Mar 2017",
    year: 2017,
    month: "Mar",
  },
  {
    id: 10,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2017",
    year: 2017,
    month: "Jan",
  },
  {
    id: 11,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2018",
    year: 2018,
    month: "Jan",
  },
  {
    id: 12,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2018",
    year: 2018,
    month: "Feb",
  },
  {
    id: 13,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2014",
    year: 2014,
    month: "Jan",
  },
  {
    id: 14,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2014",
    year: 2014,
    month: "Feb",
  },
  {
    id: 15,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Mar 2014",
    year: 2014,
    month: "Mar",
  },
  {
    id: 16,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2015",
    year: 2015,
    month: "Feb",
  },
  {
    id: 17,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2015",
    year: 2015,
    month: "Feb",
  },
  {
    id: 18,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2016",
    year: 2016,
    month: "Jan",
  },
  {
    id: 19,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2016",
    year: 2016,
    month: "Jan",
  },
  {
    id: 20,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2017",
    year: 2017,
    month: "Feb",
  },
  {
    id: 21,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2017",
    year: 2017,
    month: "Jan",
  },
  {
    id: 22,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Jan 2017",
    year: 2017,
    month: "Jan",
  },
  {
    id: 23,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Mar 2018",
    year: 2018,
    month: "Mar",
  },
  {
    id: 24,
    img: "https://cdn.hiconsumption.com/wp-content/uploads/2022/10/Meta-Quest-Pro-1-1000x667.jpg",
    title: "AjnaLens released AjnaXR Enterprise edition 2",
    releaseTitle: "LATEST PRESS RELEASES",
    releaseOn: "23 Feb 2018",
    year: 2018,
    month: "Feb",
  },
];